name: Pull request labeler
on: [ push_request_target ]

permissions:
  contents: read
  pull-requests: write

jobs:
  triage:
    runs-on: windows-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.ARTIFACTORY_TOKEN }}
