name: test
on: push

permissions:
  contents: read
  pull-requests: write

jobs:
  triage:
    runs-on: windows-latest
    environment: production
    steps:
      - uses: actions/labeler@v4
        with:
          environment-token: ${{ secrets.ARTIFACTORY_TOKEN }}
